CREATE TABLE IF NOT EXISTS USER(
	address VARCHAR(255) NOT NULL PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL UNIQUE,
	picture VARCAHR(255),
	Wallet_description VARCHAR(255),
	authenticated BOOLEAN
);

CREATE TABLE IF NOT EXISTS INVITE(
	code VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS REFERAL(
	code VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	referal VARCHAR(255) NOT NULL,

	FOREIGN KEY (referal) REFERENCES INVITE(code)
);

CREATE TABLE IF NOT EXISTS FILE_TYPE(
	type VARCHAR(5) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MEME(
	meme_id VARCHAR(255) PRIMARY KEY,
	creator_id VARCHAR(255) NOT NULL,
	contract_address VARCHAR(255) NOT NULL,
	token_id VARCHAR(255) NOT NULL,
	title VARCHAR(255),
	subtitle VARCHAR(255),
	description VARCHAR(255),
	file BLOB NOT NULL,
	file_type VARCHAR(255) NOT NULL,
	origine VARCHAR(55) NOT NULL,
	max_instance INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (file_type) REFERENCES FILE_TYPE(type)
);

CREATE TABLE IF NOT EXISTS OWNED_MEME(
	user_address VARCHAR(255) NOT NULL,
	meme_id VARCHAR(255) NOT NULL,
	sender_address VARCHAR(255),
	valid BOOLEAN DEFAULT 1,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_address) REFERENCES USER(address)
	FOREIGN KEY (sender_address) REFERENCES USER(addess)
	FOREIGN KEY (meme_id) REFERENCES MEME(meme_id)
);

CREATE TABLE IF NOT EXISTS MEME_NEWS(
	news_id VARCHAR(255) PRIMARY KEY,
	meme_id VARCHAR(255) NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(255),
	subtitle VARCHAR(255),
	url VARCHAR(255),

	FOREIGN KEY (meme_id) REFERENCES MEME(meme_id)
);

CREATE TABLE IF NOT EXISTS PLATFORM(
	name VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS REACTION(
	name VARCHAR(50) PRIMARY KEY 
);

CREATE TABLE IF NOT EXISTS MEME_REACTION(
	reaction_id VARCHAR(255) PRIMARY KEY,
	meme_id VARCHAR(255) NOT NULL,
	reaction_type VARCHAR(255) NOT NULL,
	originator_address VARCHAR(255) NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (meme_id) REFERENCES MEME(meme_id),
	FOREIGN KEY (reaction_type) REFERENCES REACTION(name),
	FOREIGN KEY (originator_address) REFERENCES USER(address)
);

CREATE TABLE IF NOT EXISTS SHARED(
	meme_reaction_id VARCHAR(255) NOT NULL,
	platform VARCHAR(255) NOT NULL PRIMARY KEY,

	FOREIGN KEY (platform) REFERENCES PLATFORM(name)
);


CREATE TABLE IF NOT EXISTS MEME_COMMENT(
	comment_id VARCHAR(255) PRIMARY KEY,
	reaction_id VARCHAR(255) NOT NULL,
	comment VARCHAR(255) NOT NULL,

	FOREIGN KEY (reaction_id) REFERENCES MEME_REACTION(reaction_id)
);

CREATE TABLE IF NOT EXISTS REPLY(
	comment_id VARCHAR(255) NOT NULL,
	comment VARCHAR(255) NOT NULL,

	FOREIGN KEY (comment_id) REFERENCES MEME_COMMENT(comment_id)
);
